name: .NET Tests

on:
  push:
    branches: [ "main", "lab_1" ]
  pull_request:
    branches: [ "main", "lab_1" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./Airline/Airline.sln

    - name: Build solution
      run: dotnet build ./Airline/Airline.sln --no-restore

    - name: Run tests
      run: dotnet test ./Airline/Airline.Tests/Airline.Tests.csproj --no-build --verbosity detailed